version: '3.8'
services:
    caddy:
        container_name: caddy
        build:
            context: .
            dockerfile: ./caddy/Dockerfile
            args:
                DOMAIN: ${DOMAIN}
                EMAIL: ${EMAIL}
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - ./caddy/data:/data #cert path
          - ./caddy/config:/config
          - ./caddy/logs:/var/log/caddy
          - ./app:/home/app
        env_file:
          - .env

    pocketbase:
        container_name: pocketbase
        build:
            context: .
            dockerfile: ./pocketbase/Dockerfile
            args:
                PB_VERSION: ${PB_VERSION}
        depends_on:
            - caddy
        ports:
            - "8090:8090"
        env_file:
            - .env
        volumes:
            - ./pocketbase/pb_data:/home/pocketbase/pb_data

    code-server:
        container_name: code-server
        build:
            context: .
            dockerfile: ./code-server/Dockerfile
            args:
                CERT: ${CERT}
                CERT_KEY: ${CERT_KEY}
                password: ${PASSWORD}
        depends_on:
            - caddy
        ports:
            - "8080:8080"
        env_file:
            - .env
        volumes:
            - ./caddy/data:/data
            - ./app:/home/app

    next-app:
        container_name: next-app 
        build:
            context: .
            dockerfile: ./app/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app/next-app:/usr/src/app
        command: npm run dev
